FROM rahusona/jnlp-slave:4.13.3-1-alpine-jdk11

ENV TERRAFORM_VERSION=1.3.6

USER root

RUN apk update \
    && apk --no-cache --no-progress add \
        openssh-client \
        ssh-askpass \
        ca-certificates \
        tar \
        zip \
        unzip \
        wget \
        curl \
        git \
        build-base \
        less \
        nano \
        tree \
        jq \
        python3 \
        py3-pip \
        groff \
        rlwrap \
        rsync \
        maven \
        bind-tools \
        aws-cli \
        procps \
    && curl -o /usr/bin/aws-iam-authenticator h
